export const actionTypes = {
    USER_LOADED : "USER_LOADED",
    LOGIN: "LOGIN",
    LOG_OUT: "LOG_OUT",
    REGISTER: "REGISTER",
    GETINFOUSER: "GETINFOUSER",
    GET_DETAIL_USER: "GET_DETAIL_USER",
}