export const actionTypes = {
    LOAD_CART: "LOAD_CART",
    DELETE_PRODUCT_CART: "DELETE_PRODUCT_CART",
    DELETE_ALL_PRODUCT_CART : "DELETE_ALL_PRODUCT_CART",
    ADD_PRODUCT_CART: "ADD_PRODUCT_CART",
    IN_DECREASE_QUANTITY : "IN_DECREASE_QUANTITY"
}