export const actionTypes = {
    CREATE_PRODUCT:"CREATE_PRODUCT",
    GET_DETAIL_PRODUCT :"GET_DETAIL_PRODUCT",
    GET_LIST_SEARCH_PRODUCT :" GET_LIST_SEARCH_PRODUCT",
    GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
    GET_ALL_CATEGORY: "GET_ALL_CATEGORY",
    GET_BY_ID_CATEGORY:"GET_BY_ID_CATEGORY",
    GET_BRAND_BY_ID_CATEGORY :"GET_BRAND_BY_ID_CATEGORY",
    GET_ALL_BRAND : "GET_ALL_BRAND",
    GET_ALL_BRAND_BY_ID : 'GET_ALL_BRAND_BY_ID',
    LAY_DANH_SACH_SAN_PHAM_PHAN_TRANG : "LAY_DANH_SACH_SAN_PHAM_PHAN_TRANG",
}