export const actionTypes = {
    GET_ALL_ORDER: "GET_ALL_ORDER",
    GET_ALL_ORDER_BY_IDCUSTOMER: "GET_ALL_ORDER_BY_IDCUSTOMER",
    GET_ALL_METHOD_PAYMENT: "GET_ALL_METHOD_PAYMENT",
    GET_ALL_METHOD_SHIPPING : "GET_ALL_METHOD_SHIPPING"
}